namespace: proxy

image:
  repository: teachindevacr.azurecr.io/proxy
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecret:
  enabled: true
  name: acr-secret

# Default proxy settings
targetServiceName: manager
targetServicePort: 80
scaleUp: 1
scaleDown: 0
inactivity: 300
scaleWait: 90
checkInterval: 30
logLevel: INFO