{{- if .Values.manager.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ printf "%s-learning-manager-ingress" (default .Release.Namespace .Values.namespace.name) }}"
  namespace: "{{ .Release.Namespace }}"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/upstream-vhost: teachin.api.{{ include "app.namespace" . }}
    {{- if and .Values.learning-manager.ingress.tls.enabled .Values.learning-manager.ingress.tls.clusterIssuer }}
    cert-manager.io/cluster-issuer: "{{ .Values.manager.ingress.tls.clusterIssuer }}"
    {{- end }}
spec:
  ingressClassName: "nginx"
  {{- if .Values.learning-manager.ingress.tls.enabled }}
  tls:
    - hosts:
        - "{{ .Values.learning-manager.ingress.host }}"
      secretName: "{{ .Values.learning-manager.ingress.tls.secretName }}"
  {{- end }}
  rules:
    - host: "{{ .Values.learning-manager.ingress.host }}"
      http:
        paths:
          - path: "{{ printf "%s/%s(/|$)(.*)" .Values.learning-manager.ingress.basePath .Release.Namespace }}"
            pathType: ImplementationSpecific
            backend:
              service:
                {{- if .Values.keda.enabled }}
                name: keda-interceptor-{{ include "app.namespace" . }}
                port:
                  number: 8080
                {{- else }}
                name: {{ .Values.learning-manager.name }}
                port:
                  number: {{ .Values.learning-manager.ports.service }}
                {{- end }}
{{- end }}
