apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: manager-image-updater
  namespace: argocd
spec:
  # בוחר את ה־Deployment לפי namespace ושם
  appSelector:
    matchNames:
      - manager
  interval: 5m # בדיקה כל 5 דקות
  images:
    - name: teachindevacr.azurecr.io/manager
      updateStrategy: latest
  git:
    url: https://github.com/ZionetLearning/learning-teachin-zionet.git
    branch: main
    commitMessage: "chore: update manager image by ArgoCD Image Updater"
