{{- if .Values.redis.useAzureRedis }}
# ExternalSecret for Azure Redis (only created when using Azure Redis)
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-connection
  namespace: {{ include "app.namespace" . }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-backend
    kind: ClusterSecretStore
  target:
    name: redis-connection
  data:
    - secretKey: redis-hostport
      remoteRef:
        key: "{{ .Values.namespace.name }}-redis-hostport"
    - secretKey: redis-password
      remoteRef:
        key: "{{ .Values.namespace.name }}-redis-password"
{{- end }}
