{{- if .Values.accessor.secrets.avatars.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.accessor.secrets.avatars.name }}
  namespace: {{ include "app.namespace" . }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-backend
    kind: ClusterSecretStore
  target:
    name: {{ .Values.accessor.secrets.avatars.name }}
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        {{ .Values.accessor.secrets.avatars.key }}: |
          {{`{{ .connectionString }}`}}
  data:
    - secretKey: connectionString
      remoteRef:
        key: {{ .Values.global.environment }}-avatars-storage-connection
{{- end }}