apiVersion: v1
kind: ServiceAccount
metadata:
  name: proxy
  namespace: {{ include "app.namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: proxy-cluster-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "patch", "update"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: proxy-cluster-rolebinding
subjects:
- kind: ServiceAccount
  name: proxy
  namespace: {{ include "app.namespace" . }}
roleRef:
  kind: ClusterRole
  name: proxy-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: {{ include "app.namespace" . }}
spec:
  selector:
    app: proxy
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: {{ include "app.namespace" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      serviceAccountName: proxy
      {{- if .Values.global.imagePullSecret.enabled }}
      imagePullSecrets:
      - name: {{ .Values.global.imagePullSecret.name }}
      {{- end }}
      containers:
      - name: proxy
        image: "{{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.tag | default .Values.global.environment }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - containerPort: 8000
        env:
        - name: TARGET_SERVICE_NAME
          value: "{{ .Values.proxy.targetServiceName }}"
        - name: NAMESPACE
          value: "{{ .Values.global.environment }}"
        - name: TARGET_SERVICE_PORT
          value: "{{ .Values.proxy.targetServicePort }}"
        - name: SCALE_UP_REPLICAS
          value: "{{ .Values.proxy.scaleUp }}"
        - name: SCALE_DOWN_REPLICAS
          value: "{{ .Values.proxy.scaleDown }}"
        - name: INACTIVITY_TIMEOUT
          value: "{{ .Values.proxy.inactivity }}"
        - name: MAX_SCALEUP_WAIT
          value: "{{ .Values.proxy.scaleWait }}"
        - name: CHECK_INTERVAL
          value: "{{ .Values.proxy.checkInterval }}"
        - name: LOG_LEVEL
          value: "{{ .Values.proxy.logLevel }}"
