{{- if .Values.proxy.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: proxy
  namespace: {{ include "app.namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: proxy-role
  namespace: {{ include "app.namespace" . }}
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["get", "list", "patch", "update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: proxy-rolebinding
  namespace: {{ include "app.namespace" . }}
subjects:
- kind: ServiceAccount
  name: proxy
  namespace: {{ include "app.namespace" . }}
roleRef:
  kind: Role
  name: proxy-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: {{ include "app.namespace" . }}
spec:
  selector:
    app: proxy
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: {{ include "app.namespace" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      serviceAccountName: proxy
      {{- if .Values.global.imagePullSecret.enabled }}
      imagePullSecrets:
      - name: {{ .Values.global.imagePullSecret.name }}
      {{- end }}
      {{- include "app.spot.affinity" . | nindent 6 }}
      {{- include "app.spot.tolerations" . | nindent 6 }}
      containers:
      - name: proxy
        image: "{{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.tag | default .Values.global.environment }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - containerPort: 8000
        env:
        - name: TARGET_SERVICES_NAME
          value: "{{ .Values.proxy.targetServicesName }}"
        - name: FORWARD_TO_SERVICE
          value: "{{ .Values.proxy.forwardToService }}"
        - name: NAMESPACE
          value: {{ include "app.namespace" . }}
        - name: TARGET_SERVICE_PORT
          value: "{{ .Values.proxy.targetServicePort }}"
        - name: SCALE_UP_REPLICAS
          value: "{{ .Values.proxy.scaleUp }}"
        - name: SCALE_DOWN_REPLICAS
          value: "{{ .Values.proxy.scaleDown }}"
        - name: INACTIVITY_TIMEOUT
          value: "{{ .Values.proxy.inactivity }}"
        - name: MAX_SCALEUP_WAIT
          value: "{{ .Values.proxy.scaleWait }}"
        - name: CHECK_INTERVAL
          value: "{{ .Values.proxy.checkInterval }}"
        - name: FORWARD_TIMEOUT
          value: "60.0"
{{- end }}