{{- if and .Values.redis.enabled (not .Values.redis.useAzureRedis) }}
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  redis-password: {{ .Values.redis.password | b64enc }}
{{- end }}
